import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import SessionProvider from '../providers/session-provider'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getServerSession(authOptions)
    return (
        <html lang="en">
            <SessionProvider session={session}>
                <body>{children}</body>
            </SessionProvider>
        </html>
    )
}
